export enum Page {
    BROWSE_EVENT_REQUEST = "BROWSE_EVENT_REQUEST",
    BROWSE_FINANCIAL_REQUEST = "BROWSE_FINANCIAL_REQUEST",
    BROWSE_HIRING_REQUEST = "BROWSE_HIRING_REQUEST",
    HOME = "HOME",
    SUBMIT_EVENT_REQUEST = "SUBMIT_EVENT_REQUEST",
    SUBMIT_HIRING_REQUEST = "SUBMIT_HIRING_REQUEST",
}
